name: Generate Snake Game

on:
  schedule: # Runs daily at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate Snake Game from contributions
        uses: Platane/snk@master
        with:
          github_user_name: AaryA164   # <-- Your GitHub username
          outputs: dist/github-contribution-grid-snake.svg
          color_snake: "#3776AB"   # Python blue
          color_dots: "#FF9900"    # AWS orange food

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
