name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch: # Manual run
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create dist folder
        run: mkdir -p dist

      - name: Generate Snake Game SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AaryA164
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Generate Snake Game (Dark Mode)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AaryA164
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          args: --palette github-dark

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
